### ISSUE TITLE
Banner: FOCU issue

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#115]
![2016-05-23_1210](https://cloud.githubusercontent.com/assets/13309806/15462290/5e7cc0fe-20df-11e6-9176-ea80b8b729e3.png)

**Comment by euveng** [comment]
Unable to replicate, perhaps send a video screencast.

**Comment by ravi-josyula** [comment]
Not fixed,
Observe this error from Safari Browser clearly

**Comment by euveng** [comment]
Unable to replicate, perhaps send a video screencast.

**Comment by roseliesromeo** [comment]
http://www.screencast.com/users/RSumido/folders/Snagit/media/6f86e296-8245-415c-a00f-902fb26430b6

**Comment by roseliesromeo** [comment]
If you open the site in IE11 it will look like this
![image](https://cloud.githubusercontent.com/assets/11186313/15885252/8d129d5c-2d88-11e6-8140-628da8fd5871.png)

**Comment by euveng** [comment]
Fixed. There was a problem with one of the script which caused the fouc in IE.
