### ISSUE TITLE
Leadins: Heading color is incorrect, it should be #e40101

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#116]
![2016-05-23_1211](https://cloud.githubusercontent.com/assets/13309806/15462375/11489726-20e0-11e6-815e-8c6cf56e1204.png)

**Comment by euveng** [comment]
color: hsl(0, 99%, 45%) is the equivalent of #e40101

Press Shift + Ctrl + the colour swatch in the inspector panel and you will see what I mean.
