### ISSUE TITLE
Home Page: Page content should cater to 8 lines as per scope

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#125]
![2016-05-23_1301](https://cloud.githubusercontent.com/assets/13309806/15463362/8e5a1df6-20e6-11e6-8de4-a4dfe9d52f5c.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ravi-josyula** [comment]
since it is not fixed

**Comment by euveng** [comment]
Fixed.
