### ISSUE TITLE
Projects page : W3C errors

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#13]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcseglobal.stage.titanweb.com.au%2Fprojects%2F

![showing results for http---cseglobal stage titanweb com au-projects- - nu html checker 2016-04-22 11-28-45](https://cloud.githubusercontent.com/assets/13309806/14733041/7f049f56-087d-11e6-8dd3-58d964070060.png)

**Comment by adrian-chan-titan** [comment]
corrected w3c errors
