### ISSUE TITLE
Home - Keep Connected: Color of the business detials titles should be #a1b1bc, it is #ffffff now

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#136]

**Comment by euveng** [comment]
Please provide more detail in your issue.

**Comment by ravi-josyula** [comment]
Sure, Please see the following screenshot provided

![2016-06-03_1413](https://cloud.githubusercontent.com/assets/13309806/15773650/bd64258a-2995-11e6-93b8-305db5547ddb.png)

**Comment by euveng** [comment]
Fixed.
