### ISSUE TITLE
HSEQ page : W3C errors

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#14]
Applicable for Careers page and contact us page also.

https://validator.w3.org/nu/?doc=http%3A%2F%2Fcseglobal.stage.titanweb.com.au%2Fhseq%2F

![showing results for http---cseglobal stage titanweb com au-hseq- - nu html checker 2016-04-22 11-30-48](https://cloud.githubusercontent.com/assets/13309806/14733085/ce659f14-087d-11e6-9fac-f3349ffb05a3.png)

https://validator.w3.org/nu/?doc=http%3A%2F%2Fcseglobal.stage.titanweb.com.au%2Fcontact-us%2F

https://validator.w3.org/nu/?doc=http%3A%2F%2Fcseglobal.stage.titanweb.com.au%2Fcareers%2F

**Comment by adrian-chan-titan** [comment]
Errors fixed in global templates

**Comment by adrian-chan-titan** [comment]
Errors has been fixed
