### ISSUE TITLE
Sidebar -Contact Form: Only 3 fields should be required as per the standards

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#144]
https://knowledgebase.titanweb.com.au/implementation/gravity-forms-implementation/mandatory-required-fields
![2016-05-23_1422](https://cloud.githubusercontent.com/assets/13309806/15465447/32562d0e-20f2-11e6-83cd-34dfbf4e6663.png)

**Comment by euveng** [comment]
Fixed.
