### ISSUE TITLE
Key Managment Page: Don't use watermarked images

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#148]
https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/using-images
![2016-05-23_1453](https://cloud.githubusercontent.com/assets/13309806/15466286/6f4f746e-20f6-11e6-86cc-736f953b13f5.png)

**Comment by adrian-chan-titan** [comment]
The watermark is part of the image and used only for design. Once the proper image is used, there will be no watermark

**Comment by euveng** [comment]
Fixed.
