### ISSUE TITLE
Admin : Custom Fields - some fields are not hidden

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#16]
https://knowledgebase.titanweb.com.au/implementation/advanced-custom-fields-implementation/advanced-custom-fields-options
Companies, Staff profiles, Gallery, Home page settings, Banner links, Theme options
![2016-04-22_1500](https://cloud.githubusercontent.com/assets/13309806/14737714/28dceffc-089b-11e6-868f-09c2e2416129.png)

**Comment by adrian-chan-titan** [comment]
Fixedd
