### ISSUE TITLE
Header - Menu: Dropdown arrow icon is showing @1199 Viewport

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#177]
![2016-06-03_1626](https://cloud.githubusercontent.com/assets/13309806/15776798/22ba9e66-29a8-11e6-8c4e-954b30c6e0d6.png)

**Comment by euveng** [comment]
This is necessary so that this toggle is available on ipad at 1024px. This gets hidden above 1200px, will not fix.

**Comment by roseliesromeo** [comment]
Not necessary in iPad landscape.  It should just be the same in desktop. Please remove.

**Comment by euveng** [comment]
The dropdown arrow plays an even more important role in ipad because there is no other way to activate the dropdown menu. The main navbar links themselves are active links and do not activate the dropdown without linking off to another page.

**Comment by roseliesromeo** [comment]
Actually there is a way to activate the drop down even without the arrows.  It's  been done in most sites already unless specified in the design to add drop down arrows. See below example.
What's been done is, first tap would be to activate the drop down menu. 2nd tap would be to link to the page.
![image](https://cloud.githubusercontent.com/assets/11186313/15961773/42589fe8-2f39-11e6-997b-467f1e7e8de8.png)
