### ISSUE TITLE
Home -Welcome: Viewmore button is not applicable in Safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#182]
![2016-06-03_1649](https://cloud.githubusercontent.com/assets/13309806/15777224/360d8b88-29ab-11e6-91a6-2440bd83bfbe.png)

**Comment by euveng** [comment]
Unable to reproduce issue.

**Comment by roseliesromeo** [comment]
We no longer support safari browser.
