### ISSUE TITLE
Home - Latest News: Posts are getting distorted in Safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#183]
![2016-06-03_1650](https://cloud.githubusercontent.com/assets/13309806/15777257/6e307dd6-29ab-11e6-94b5-f6ec1d2469ec.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser in desktop and no issue in iPad air.
