### ISSUE TITLE
Header - Logo: Logo streched in safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#186]
![2016-06-03_1707](https://cloud.githubusercontent.com/assets/13309806/15777531/b6258044-29ad-11e6-8fc0-e4666cc34e0d.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktop. No issue in device.
