### ISSUE TITLE
History Page: Image is streching in Safari browser while reflowing the browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#188]
![2016-06-03_1721](https://cloud.githubusercontent.com/assets/13309806/15777805/cdc60992-29af-11e6-8ee6-8d157afc04a8.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktop.
