### ISSUE TITLE
All inner pages - Sidebar: Select dropdown field should be vertically aligned with the all input fields in Safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#189]
![2016-06-03_1723](https://cloud.githubusercontent.com/assets/13309806/15777858/1f8889a8-29b0-11e6-94f6-325e8d31240e.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktop.
