### ISSUE TITLE
All inner pages : All images are streching/enlarged in safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#191]
![2016-06-03_1728](https://cloud.githubusercontent.com/assets/13309806/15777936/9d1f6fe4-29b0-11e6-963a-5c684fa218c2.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktopn.
