### ISSUE TITLE
Contact Us page: Top border of the panel is touches the google map in safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#192]
![2016-06-03_1730](https://cloud.githubusercontent.com/assets/13309806/15778003/048be432-29b1-11e6-8a15-7ead792f17e2.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktopn.
