### ISSUE TITLE
Contact Us Page -Form: Place holder text should be vertically center aligned in safari browser

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#193]
![2016-06-03_1731](https://cloud.githubusercontent.com/assets/13309806/15778050/5fc3f434-29b1-11e6-8fb2-96046300458c.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktopn.
