### ISSUE TITLE
Contact Us Page: Select dropdown background should be equals with input field in safari

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#194]
![2016-06-03_1734](https://cloud.githubusercontent.com/assets/13309806/15778076/9594ed2a-29b1-11e6-9a85-ef01d4680310.png)

**Comment by euveng** [comment]
Is this on desktop or device?

**Comment by roseliesromeo** [comment]
We no longer support safari browser for desktopn.
