### ISSUE TITLE
Conatct Us page: Accordian expandable and collapsable panels are not working(Viewport: iPad(mini) | Safari)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#195]
![2016-06-03_1736](https://cloud.githubusercontent.com/assets/13309806/15778133/da80cc74-29b1-11e6-9f5f-bcd8c3b3c13d.png)

**Comment by euveng** [comment]
Unable to reproduce this on ipad. All accordion headings are working fine.
