### ISSUE TITLE
Latest News Section :Latest News Section is not displaying below 480 resolution

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#45]
![28](https://cloud.githubusercontent.com/assets/13309806/14810186/34a4f4c6-0baf-11e6-9279-b42d29e1c91e.png)

**Comment by adrian-chan-titan** [comment]
Left out intentionally, to reduce extra scrolling needed before hitting the contacts.

**Comment by euveng** [comment]
Fixed.
