### ISSUE TITLE
History page : Horizontal seperator/Boarder is not implemented 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#49]
![1](https://cloud.githubusercontent.com/assets/13309806/14811161/59f9c242-0bb4-11e6-9bbf-ac800532d29f.png)

**Comment by adrian-chan-titan** [comment]
I've based header styles of the homepage designs and used it globally across all pages to achieve consistency. Do we usually have different header styles for internal pages?

**Comment by euveng** [comment]
Fixed.
