### ISSUE TITLE
Our Company Page :  ACF field should be implemented to upload PDF files as per design

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#61]
![edit post cse global wordpress 2016-04-26 10-42-53](https://cloud.githubusercontent.com/assets/13309806/14811921/4e8f5b98-0bb8-11e6-9c28-f05b798a9b55.png)
 Design:
![05b-cse-our-company- single](https://cloud.githubusercontent.com/assets/13309806/14811934/613374e6-0bb8-11e6-9151-55a370ee81e1.jpg)

**Comment by adrian-chan-titan** [comment]
Fixed
