### ISSUE TITLE
Products & Services  : ReasMore/ReadLess toggle functionality is not implemented properly, Its working vice versa

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#69]
![products services - cse global 2016-04-26 11-01-38](https://cloud.githubusercontent.com/assets/13309806/14812638/a4517748-0bbb-11e6-8bab-8c5301cf3f37.png)

**Comment by adrian-chan-titan** [comment]
Converted to use post single page, had issues with jquery plugin limiting by lines instead of paragraphs
