### ISSUE TITLE
HESQ Page : Featured image size should be W-870px and H-356px 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#77]
Applicable to all pages
![2016-04-26_1203](https://cloud.githubusercontent.com/assets/13309806/14813304/d439ff36-0bbe-11e6-934f-746fb4fc85cb.png)

**Comment by adrian-chan-titan** [comment]
Image and text is is controlled by bootstrap column. 
making the image larger will break the alignments.
