### ISSUE TITLE
HESQ Page : Text should align with Name Field, Applicable to all pages

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#79]
![careers - cse global 2016-04-26 12-27-53](https://cloud.githubusercontent.com/assets/13309806/14813457/649f2998-0bbf-11e6-948f-14897e86da6a.png)

**Comment by adrian-chan-titan** [comment]
Already from #76

**Comment by adrian-chan-titan** [comment]
fixed
