### ISSUE TITLE
News Page : Unnecessary icons are displaying in pagination 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#82]
![latest news - cse global 2016-04-26 12-57-21](https://cloud.githubusercontent.com/assets/13309806/14813799/09294952-0bc1-11e6-86cb-84421578e9ce.png)

**Comment by adrian-chan-titan** [comment]
Fixed in item #7

**Comment by adrian-chan-titan** [comment]
Fixed stylings
