### ISSUE TITLE
Contact us page : Contact Email should be in Bold

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#85]
![contact us - cse global 2016-04-26 12-32-27](https://cloud.githubusercontent.com/assets/13309806/14814072/4bebb260-0bc2-11e6-8894-6b60b1883bc6.png)

**Comment by adrian-chan-titan** [comment]
Fixedd

**Comment by adrian-chan-titan** [comment]
Fixed
