### ISSUE TITLE
Contact Us Page : After submitting the form, form should navigate to contact us page

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#86]
![contact us - cse global 2016-04-26 12-43-28](https://cloud.githubusercontent.com/assets/13309806/14814161/a7c900d8-0bc2-11e6-8773-acfe1d3a8183.png)

**Comment by adrian-chan-titan** [comment]
Fix to redirect to contact us thank you page consistent with the rest of the other pages

**Comment by adrian-chan-titan** [comment]
fixed
