### ISSUE TITLE
Contact Us page : Click to call is not implemented for phone numbers

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#88]
![contact us - cse global 2016-04-26 12-52-45](https://cloud.githubusercontent.com/assets/13309806/14814354/82ef5b08-0bc3-11e6-832e-c2582d33af1f.png)

**Comment by adrian-chan-titan** [comment]
fix

**Comment by adrian-chan-titan** [comment]
Fixed
