### ISSUE TITLE
Contact Form : Dropdown field is getting clipped in mobile devices

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#89]
![2](https://cloud.githubusercontent.com/assets/13309806/14814544/5d0eac6c-0bc4-11e6-88a2-2b9a0e2505a9.png)

**Comment by adrian-chan-titan** [comment]
Gravity form Dropdown ui has a bug which attachs width as an inline style to the dropdown when the it is loaded. Fixed by Implementing jquery to remove inline style when resize occurs.
