### ISSUE TITLE
Home page : W3C errors

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#9]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fcseglobal.stage.titanweb.com.au%2F

![2016-05-23_1009](https://cloud.githubusercontent.com/assets/13309806/15460420/819e6cce-20ce-11e6-9771-3e9c53f7bfb4.png)

**Comment by adrian-chan-titan** [comment]
Fixed W3C errors

**Comment by adrian-chan-titan** [comment]
Unable to reproduce this error, clicking the link at the top shows no errors. So i am unsure fo this fix.

**Comment by euveng** [comment]
The page seems to be zero error now.
