### ISSUE TITLE
News Single page : Text is overlapping with featured image in Ipad

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/CSE-Global#96]
![6](https://cloud.githubusercontent.com/assets/13309806/14816505/f66d9c10-0bce-11e6-96c1-12f5b2a28442.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ravi-josyula** [comment]
Not fixed in iPad(mini) Portrait view

**Comment by euveng** [comment]
It looks fine, see screenshot. 

![image](https://cloud.githubusercontent.com/assets/9030354/15843330/fa860ba8-2c93-11e6-8c57-6612ae46a57f.png)
